# bisogna mettere il file yml nella directory .github/workflows che se non già presente va creata
# evento che attiva
# jobs ovvero passi che vanno eseguiti
# ogni job ha un runner che lo esegue. Posso anche eseguire il job in un
# container ma il container deve avere un job che lo esegue
# i jobs contengono uno o più steps che possono essere comandi di shell o altro
# gli step dello stesso job condividono i dati quindi al primo step posso compilare
# al secondo fare la build ecc.
# le azioni infine, sono procedure che possono essere eseguite in ogni step
# EVENTI triggerano l'esecuzione, ce ne sono 35
# JOBS sono insieme di passi che usano lo stesso runner. Vanno in parallelo a meno 
# che non specifichi needs ovvero che deve aspettare che altri passi finiscano

name: CI workflow

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          flake8 service --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 service --count --max-complexity=10 --max-line-length=127 --statistics
      - name: Run unit tests with nose
        run: nosetests -v --with-spec --spec-color --with-coverage --cover-package=app